### ISSUE TITLE
globus-timer-cli stuck in auth loop

### ISSUE THREAD

**Issue by tcooper** [globus/globus-timer-cli#1]
I'm trying to use the `globus-timer-cli` to schedule a recurring transfer between two endpoints I have access to.

I've successfully tranfered between these endpoints manually by scheduling the task with the Web UI. Here is the task information from the globus-cli...

```
~/globus ❯ globus task show d2f71f40-7217-11eb-8eb8-02abbf4b2fc3
Label:                   None
Task ID:                 d2f71f40-7217-11eb-8eb8-02abbf4b2fc3
Is Paused:               False
Type:                    TRANSFER
Directories:             0
Files:                   1
Status:                  SUCCEEDED
Request Time:            2021-02-18T18:33:42+00:00
Faults:                  0
Total Subtasks:          2
Subtasks Succeeded:      2
Subtasks Pending:        0
Subtasks Retrying:       0
Subtasks Failed:         0
Subtasks Canceled:       0
Subtasks Expired:        0
Completion Time:         2021-02-18T18:33:47+00:00
Source Endpoint:         SDSC XSEDE Stats
Source Endpoint ID:      a98847d0-3691-11e7-bcd6-22000b9a448b
Destination Endpoint:    Performance Data from SDSC resources for XMS
Destination Endpoint ID: de22d598-71ff-11eb-a9ad-efda19b7c028
Bytes Transferred:       1781562
Bytes Per Second:        334677
```

I've succesfully authenticated with the `globus-timer-cli`...

```
~/globus ❯ globus-timer session login
Please log into Globus here:
---------------------------
https://auth.globus.org/v2/oauth2/authorize?client_id=bc77d044-1f42-46cc-9702-87f756cd08a6&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=email+openid+profile&state=_default&response_type=code&code_challenge=[REDACTED]&code_challenge_method=S256&access_type=offline&prefill_named_grant=Globus+Timer+Command+Line+Interface+on+login01
---------------------------

Enter the resulting Authorization Code here: [REDACTED]
Logged in as tcooper@globusid.org

~/globus ❯ cat ~/.globus_timer_tokens.json
{
  "email": {
    "access_token": "[REDACTED]",
    "dependent_scopes": [],
    "expiration_time": 1620446964,
    "refresh_token": "[REDACTED]"
  },
  "openid": {
    "access_token": "[REDACTED]",
    "dependent_scopes": [],
    "expiration_time": 1620446964,
    "refresh_token": "[REDACTED]"
  },
  "profile": {
    "access_token": "[REDACTED]",
    "dependent_scopes": [],
    "expiration_time": 1620446964,
    "refresh_token": "[REDACTED]"
  },
  "urn:globus:auth:scope:transfer.api.globus.org:all": {
    "access_token": "[REDACTED]",
    "dependent_scopes": [],
    "expiration_time": 1620447015,
    "refresh_token": "[REDACTED]"
  }
}

~/globus ❯ globus-timer session whoami
tcooper@globusid.org
```
...and attempted to schedule a recurring transfer as show below...

```
~/globus ❯ globus-timer job transfer \
        --name expanse-slurm-accounting \
        --label 'EXPANSE Slurm Accounting Logs to XDMoD' \
        --interval 28800 \
        --start '2021-05-05T07:00:00-0700' \
        --source-endpoint b256c034-1578-11eb-893e-0a5521ff3f4b \
        --dest-endpoint de22d598-71ff-11eb-a9ad-efda19b7c028 \
        --item /expanse/lustre/projects/sds185/bnk_svc/expanse/accounting /expanse/accounting true
Please log into Globus here:
---------------------------
https://auth.globus.org/v2/oauth2/authorize?client_id=bc77d044-1f42-46cc-9702-87f756cd08a6&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall&state=_default&response_type=code&code_challenge=[REDACTED]&code_challenge_method=S256&access_type=offline&prefill_named_grant=Globus+Timer+Command+Line+Interface+on+login01
---------------------------

Enter the resulting Authorization Code here: [REDACTED]
Please log into Globus here:
---------------------------
https://auth.globus.org/v2/oauth2/authorize?client_id=bc77d044-1f42-46cc-9702-87f756cd08a6&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=https%3A%2F%2Fauth.globus.org%2Fscopes%2F524230d7-ea86-4a52-8312-86065a9e0417%2Ftransfer_action%5Bhttps%3A%2F%2Fauth.globus.org%2Fscopes%2Factions.globus.org%2Ftransfer%2Ftransfer%5D&state=_default&response_type=code&code_challenge=[REDACTED]&code_challenge_method=S256&access_type=offline&prefill_named_grant=Globus+Timer+Command+Line+Interface+on+login01
---------------------------

Enter the resulting Authorization Code here: ^CAborted!
```

You should be able to witness that I'm repeatedly asked to authenticate and the task is never scheduled.

If I go into the Manage Consents WebUI I can see multiple authorizations there.

It seems like the `globus-timer-cli` cannot access my token file or the login I'm using in Globus (tcooper@globusid.org) is not valid. I'm using the same login credentials in `globus-timer-cli` as I am in the `globus-cli` and in the Globus WebUI.

Please advise an how to troubleshoot this issue or suggest an alternate mechanism to setup scheduled transfers between two endpoints.

**Comment by rpwagner** [comment]
@tcooper I was able to submit a recurring transfer between one of my personal endpoints and a guest collection. However, I did have to go through several auth steps to get the OAuth scopes required. It looks like the CLI tool isn't asking for all the necessary scopes up front. You can see that if you look at the second URL you pasted.

@jimPruyne would it be possible to ask for all the scopes when first doing the `globus-timer session login` step, since this is a CLI tool appears to be dedicated to a single Automate Flow? If needed, you could host the scopes on a trusted URL in case you need to update the Flow and scope changes.

**Comment by jimPruyne** [comment]
Hi Rick, nice to see you around again!
    We'd have to look again at the Auth steps. I realize it is
      somewhat arduous and perhaps off-putting to have to go through
      multiple round trips with Auth. We'd have to swap back in on that
      to see if those multiple round-trips are more a matter of
      convenience for us as developers or if there's a strict reason why
      it is necessary.
    My inclination as I think through it again is that it is
      necessary. What's happening here is that GCS v5.4 collections
      define their own Globus Auth scope for data access. We do not know
      until we ask Globus Transfer whether a particular collection
      requested needs this extra scope. So, we first need to get
      authorization to communicate with Transfer to retrieve the
      collection definitions. In the case where additional consents are
      required to interact with GCS, we'll have to ask you again via
      another round of Globus Auth interactions to get those consents in
      place.
    The first round of Auth interactions, getting consent to work
      with Transfer, should only happen the first time you use the CLI.
      After that, the tokens for consenting to work with Transfer should
      be cached and re-used on any other calls. Thus, if you schedule
      another timer session, the only consent you may be asked for is
      working with a previously unused GCS collection if that is part of
      your Timer job.
    Does this make sense? Feel free to hit us up again for further
      discussion if you want.
    Best,
    --- Jim
    
    
    On 5/7/21 8:46 PM, Rick Wagner wrote:
    
    
      
      @tcooper
        I was able to submit a recurring transfer between one of my
        personal endpoints and a guest collection. However, I did have
        to go through several auth steps to get the OAuth scopes
        required. It looks like the CLI tool isn't asking for all the
        necessary scopes up front. You can see that if you look at the
        second URL you pasted.
      @jimPruyne
        would it be possible to ask for all the scopes when first doing
        the globus-timer session login step, since this is
        a CLI tool appears to be dedicated to a single Automate Flow? If
        needed, you could host the scopes on a trusted URL in case you
        need to update the Flow and scope changes.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/globus/globus-timer-cli/issues/1#issuecomment-834948628",
"url": "https://github.com/globus/globus-timer-cli/issues/1#issuecomment-834948628",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tcooper** [comment]
@rpwagner / @jimPruyne : Indeed, completing a series of 4 (four) authentications does produce a scheduled job using `globus-timer`.

#### setting up timer job
```bash
~/globus ❯ globus-timer job transfer \
        --name my-transfer \
        --label 'My Transfer' \
        --interval 28800 \
        --start '2021-05-10T07:00:00-0700' \
        --source-endpoint b256c034-1578-REDACTED-0a5521ff3f4b \
        --dest-endpoint de22d598-71ff-REDACTED-efda19b7c028 \
        --item /source/directory /destination/directory/ true
Please log into Globus here:
---------------------------
https://auth.globus.org/v2/oauth2/authorize?client_id=bc77d044-1f42-REDACTED-87f756cd08a6&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=urn%3Aglobus%3Aauth%3Ascope%3Atransfer.api.globus.org%3Aall&state=_default&response_type=code&code_challenge=REDACTED&code_challenge_method=S256&access_type=offline&prefill_named_grant=Globus+Timer+Command+Line+Interface+on+localhost
---------------------------

Enter the resulting Authorization Code here: [PASTE]+[ENTER]
Please log into Globus here:
---------------------------
https://auth.globus.org/v2/oauth2/authorize?client_id=bc77d044-1f42-REDACTED-87f756cd08a6&redirect_uri=https%3A%2F%2Fauth.globus.org%2Fv2%2Fweb%2Fauth-code&scope=https%3A%2F%2Fauth.globus.org%2Fscopes%2F524230d7-ea86-REDACTED-86065a9e0417%2Ftransfer_action%5Bhttps%3A%2F%2Fauth.globus.org%2Fscopes%2Factions.globus.org%2Ftransfer%2Ftransfer%5D&state=_default&response_type=code&code_challenge=REDACTED&code_challenge_method=S256&access_type=offline&prefill_named_grant=Globus+Timer+Command+Line+Interface+on+localhost
---------------------------

Enter the resulting Authorization Code here: [PASTE]+[ENTER]
Name:            my-transfer
Job ID:          9a892341-e0ea-REDACTED-984d5c874f68
Status:          new
Start:           2021-05-10T14:00:00+00:00
Interval:        8:00:00
Next Run At:     2021-05-10T22:00:00+00:00
Last Run Result: NOT RUN
```

#### listing timer job
```bash
~/globus ❯ globus-timer job list
Name                     | Job ID                               | Status | Last Result
-------------------------|--------------------------------------|--------|-------------
my-transfer | 9a892341-e0ea-REDACTED-984d5c874f68 | loaded | RUN COMPLETE
```

#### job status after run
```
~/globus ❯ globus-timer job status 9a892341-e0ea-REDACTED-984d5c874f68
Name:            my-transfer
Job ID:          9a892341-e0ea-REDACTED-984d5c874f68
Status:          loaded
Start:           2021-05-10T14:00:00+00:00
Interval:        8:00:00
Next Run At:     2021-05-10T22:00:00+00:00
Last Run Result: RUN COMPLETE
```

I will reiterate a request that the documentation and/or UI be updated for the benefit of those that follow me.

The prompt for each of the 4 separate authentications required to schedule this job, I only posted the last two here, "**Please log into Globus here**:" followed by "**Enter the resulting Authorization Code here:**" give no indication that the process flow is operating as expected.

On my first attempts to do this I bailed after the third apparent failure and tried the sequence two times. If I had persisted to the fourth copy/paste I would have scheduled the job but would have had no clue why it worked thinking I had somehow copy and pasted incorrectly 3 times.

Thanks for your help.
