### ISSUE TITLE
Default permissions on token_store are not secure

### ISSUE THREAD

**Issue by tcooper** [globus/globus-timer-cli#2]
When writing new `token_store` to `DEFAULT_TOKEN_FILE` likely here...

https://github.com/globus/globus-timer-cli/blob/58633637e4bdb19995abc5237ecc8546a6f19278/timer_cli/auth.py#L104-L119

...the permissions of the `DEFAULT_TOKEN_FILE` file **are not secure**.

The default behavior for the creation of the `DEFAULT_TOKEN_FILE` should be to create it with octal mode `0o600`.

For example...
```
original_umask = os.umask(0o177)  # 0o777 ^ 0o600
try:
    with os.fdopen(os.open(filename, os.O_WRONLY | os.O_CREAT, 0o600), 'w') as fp:
        json.dump(tokens, fp, indent=4, separators=(", ", ": "))
finally:
    os.umask(original_umask)
```

**Comment by rudyardrichter** [comment]
Thank you very much @tcooper for pointing out this issue as well as providing that helpful snippet. A fix will be included in the next release to PyPI.
